# Generated by Django 4.0.4 on 2022-10-25 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.author'),
            preserve_default=False,
        ),
    ]
