# Generated by Django 4.0.4 on 2022-10-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_author_options_alter_author_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
