# Generated by Django 4.0.4 on 2022-10-28 21:44

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_author_author_name_alter_author_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_name',
            field=models.CharField(default=2, max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
