# Generated by Django 4.0.4 on 2022-10-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_author_author_name_alter_author_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_name',
        ),
    ]
