# Generated by Django 4.1.2 on 2022-10-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.DateField(),
        ),
    ]
