# Generated by Django 4.1.2 on 2022-10-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_book_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.CharField(max_length=255),
        ),
    ]
