# Generated by Django 4.1.2 on 2022-10-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=60)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('publish_date', models.DateField(blank=True)),
            ],
        ),
    ]
