# Generated by Django 4.1.1 on 2022-10-27 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
