# Generated by Django 4.1.2 on 2022-10-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
